[package]
name = "swarm-mod-vanilla-boss"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.19", default-features = false }
serde = { version = "1", features = ["derive"] }
swarm-engine = { git = "https://github.com/game-swarm/engine.git", rev = "fc1286401cdea0e6e4a4e3aef931e50b35dcc6e0" }
